### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mst-ableton** [factset/quart-openapi#36]
Hey, would it be possible to cut a new release sometime soon? The changes in https://github.com/factset/quart-openapi/pull/35 clean up something that's been deprecated in Python 3.8, but those changes weren't included in `1.5.0`. Thanks!

**Comment by zeroshade** [comment]
Sure! It's midnight at the moment, but I'll cut a release in the morning.

**Comment by zeroshade** [comment]
version [1.5.1](https://github.com/factset/quart-openapi/releases/tag/1.5.1) released
