### ISSUE TITLE
Update to support Quart 0.11.0

### ISSUE THREAD

**Issue by ttran** [factset/quart-openapi#38]
New version released today from Quart 0.10.0 to 0.11.0 breaks quart-openapi.

**Comment by basilfx** [comment]
+1. It fails with:

```
  File "foo/server/webserver.py", line 3, in <module>
    from quart_openapi import Pint, Resource
  File "env/lib/python3.7/site-packages/quart_openapi/__init__.py", line 13, in <module>
    from .swagger import Swagger
  File "env/lib/python3.7/site-packages/quart_openapi/swagger.py", line 13, in <module>
    from quart.routing import ROUTE_VAR_RE
ImportError: cannot import name 'ROUTE_VAR_RE' from 'quart.routing' (env/lib/python3.7/site-packages/quart/routing.py)
```

**Comment by pgjones** [comment]
I think you'd need to switch the code to use `werkzeug.routing._rule_re` (Quart's routing is now done by Werkzeug).

Sorry about this, it has never occurred to me that `ROUTE_VAR_RE` would be used outside of Quart itself.

**Comment by zeroshade** [comment]
@pgjones thanks, I planned on getting to this today so your comment saves me some work. I should have something up and push out the new version in the next hour or so

**Comment by zeroshade** [comment]
https://github.com/factset/quart-openapi/releases/tag/v1.5.2 has been released fixing this issue

**Comment by YaoJusheng** [comment]
Are you sure this problem has been fixed?
In my code, it has a similar error.
By the way, the `quart-openapi` version I used is `1.7.2`.

The error message is as follows:
```
...
  from werkzeug.routing import _rule_re as ROUTE_VAR_RE
ImportError: cannot import name '_rule_re' from 'werkzeug.routing' ...
```

**Comment by Havanero** [comment]
ImportError: cannot import name '_rule_re' from 'werkzeug.routing'
quart-openapi version I used is 1.7.2.

**Comment by tomerh2001** [comment]
Am still getting this, any updates?

**Comment by carusyte** [comment]
same issue. quart-openapi==1.7.2

**Comment by archanasevak** [comment]
@carusyte how did you fix it?
