### ISSUE TITLE
Why no demo on how to list the documented API or to borrow your terminology, PintBlueprint

### ISSUE THREAD

**Issue by Havanero** [factset/quart-openapi#41]
Hi there,

Since restplus is dead, I'm looking for ways to migrate from flask to quart and something similar to restplus... but unfortunately i cannot follow your framework on listing the APIS once we have:
1) declare the endpoints for PintBlueprint (restplus namespace)
2) register this with Pint (quart app)
3) point to prefix /api/v1

on point 3 I would expect the listing openapi docs

**Comment by zeroshade** [comment]
If you look at the unit tests you can see examples using blueprints and retrieving the openapi docs (https://github.com/factset/quart-openapi/blob/master/tests/test_blueprints.py#L93) 

It does make sense to add some examples to the docs that have this, but is looking at the unit tests sufficient to get you going for the time being?

**Comment by zeroshade** [comment]
Gonna close this issue for now, feel free to reopen it if necessary @Havanero
