### ISSUE TITLE
Auth methods

### ISSUE THREAD

**Issue by kev11moreno** [factset/quart-openapi#43]
Hi, it's me again, sorry but I'm making experiments with your lib, my question now it's if you have a example for auth methods and at same time expose this to the json and then swagger could read it.

Sorry for my english, it'sn't my first lenguage.

**Comment by zeroshade** [comment]
I don't currently have any examples for exposing the auth methods to the swagger. But you can utilize the quart `before_request` hook in order to implement authentication. There are also several examples on there for doing so such as using the https://gitlab.com/pgjones/quart-auth plugin.
