### ISSUE TITLE
Quart 0.12 breaks API

### ISSUE THREAD

**Issue by flyinactor91** [factset/quart-openapi#45]
Quart 0.12 made a small breaking change to `Quart.add_url_rule` that causes the following error:

> `TypeError: add_url_rule() got multiple values for argument 'provide_automatic_options'`

This is because the `methods` parameters appears to have moved in the function call.

Setting `methods=methods` in `pint.py line 199` fixed this for me locally.

**Comment by zeroshade** [comment]
Thanks for pointing it out, i'll take a look and push out a fix.

**Comment by xandrade** [comment]
Hello, 

> Quart 0.12 made a small breaking change to `Quart.add_url_rule` that causes the following error:
> 
> > `TypeError: add_url_rule() got multiple values for argument 'provide_automatic_options'`
> 
> This is because the `methods` parameters appears to have moved in the function call.
> 
> Setting `methods=methods` in `pint.py line 199` fixed this for me locally.

I also got same error. Please let us know how we can support

**Comment by zeroshade** [comment]
@xandrade @flyinactor91 

quart-openapi version 1.6.0 should be deployed to pypi momentarily which will fix this issue. I'll comment again once the deploy has happened. Please give it a try afterwards and confirm that everything works fine for you both. thanks

**Comment by zeroshade** [comment]
Ok, Pypi deployment has completed, in my local testing everything worked correctly (along with the travis build) so please confirm that updating to version 1.6.0 of quart-openapi fixes the issues you were both having. :)

**Comment by flyinactor91** [comment]
Fixed it for me. Thanks for the update!
