### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by henshalb** [factset/quart-openapi#48]
add_url_rule() takes only 2 to 4 positional arguments in the Quart. But Pint takes 5 positional arguments (and 1 keyword-only argument). This raises a TypeError. Did in Quart 0.12.0 released on the 2020-05-21 to match Flask's API.

**Comment by pgjones** [comment]
Looks fixed in 5ad3e75238237b12f5bddb4125996b59aee2192c, although this is unreleased.

**Comment by henshalb** [comment]
Okay. Then I'm closing this issue.
