### ISSUE TITLE
Optional Marshmallow integration raises import error

### ISSUE THREAD

**Issue by flyinactor91** [factset/quart-openapi#50]
The `swagger.py` file is raising a missing import error when importing the optional Marshmallow support.

`from .marshmallow import MARSHMALLOW, schema_to_json`

The issue is that `schema_to_json` is not available when the `marshmallow` and `marshmallow_jsonschema` libs raise an ImportError:

```python
except ImportError:
    Schema = None
    JSONSchema = None
    MarshmallowValidationError = None
    MARSHMALLOW = False
    # No replacement for schema_to_json
```

**Comment by flyinactor91** [comment]
Tested with:

```
Quart                  0.14.1
quart-openapi          1.7.0
```

**Comment by iron-road-dev** [comment]
I get the same ImportError when using quart==0.14.1 and quart-openapi==1.7.0

Downgrading to quart==0.13.0 and quart-openapi==1.6.0 fixed the issue

**Comment by zeroshade** [comment]
@flyinactor91  @iron-road-dev  once version 1.7.1 is finished deploying to pypi, please give that a try to fix this issue.

**Comment by iron-road-dev** [comment]
@zeroshade All is well with 1.7.1; thank you for the quick turn around.
